sandbox fix to allow socketpair(AF_UNIX...) as used by tokio signal handling
proxy-routed mode sandbox fix to allow socketpair(AF_UNIX...) as used by tokio signal handling

landlock.rs is also used in the bwrap path, which is why changes are in that file

Verification:

add new tests, run  `cargo test -p codex-linux-sandbox`

Try a process that uses tokio signal handling. e.g. ratter-build --version.  Can install it with `brew install rattler-build` etc

Before:
```
codex
...
› run in sandbox: /spare/local/ahornby/.micromamba/envs/rattler-build/bin/rattler-build --version

• Ran in the sandbox. It exited with code 1 and printed:

  thread '<unnamed>' (5) panicked at .../tokio-1.51.1/src/signal/unix.rs:71:53:
  failed to create UnixStream: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  Error:   × Thread panicked
```

Local build with

```
V8_DIR=${TMPDIR:-/tmp}/rusty-v8-v146.4.0
mkdir -p "$V8_DIR"
curl -fL -o "${V8_DIR}/src_binding_release_x86_64-unknown-linux-musl.rs" "https://github.com/openai/codex/releases/download/rusty-v8-v146.4.0/src_binding_release_x86_64-unknown-linux-musl.rs"
export RUSTY_V8_ARCHIVE="https://github.com/openai/codex/releases/download/rusty-v8-v146.4.0/librusty_v8_release_x86_64-unknown-linux-musl.a.gz"
export RUSTY_V8_SRC_BINDING_PATH="${TMPDIR:-/tmp}/rusty-v8-v146.4.0/src_binding_release_x86_64-unknown-linux-musl.rs"
CODEX_SKIP_VENDORED_BWRAP=1 cargo build --release --target x86_64-unknown-linux-musl -p codex-cli --bin codex
```

After, using local build:
```
codex
...
› run in sandbox: /spare/local/ahornby/.micromamba/envs/rattler-build/bin/rattler-build --version

• Ran /spare/local/ahornby/.micromamba/envs/rattler-build/bin/rattler-build --version
  └ (no output)

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

• rattler-build 0.63.1
```

Tidiness
```
just fmt
just fix -p codex-linux-sandbox
```

Config used:
```toml
model = "gpt-5.5"
model_reasoning_effort = "medium"
approvals_reviewer = "user"

default_permissions = "workspace"

[shell]
program = "/bin/bash"
args = ["--noprofile", "--norc"]

[permissions.workspace.filesystem]
":root" = "read"
":tmpdir" = "write"

[permissions.workspace.filesystem.":project_roots"]
"." = "write"

[permissions.workspace.network]
enabled = true
# full is still filtered by domain but allows POST etc (c.f. limited)
mode = "full"
# needed to resolve local 10.* IPs
allow_local_binding = true

[permissions.workspace.network.domains]
"example.com" = "allow"
```